# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2c70258a162372eed0ab239e803088f5d1221289e63712ce5e30f12229f7cdaabda5350fb307ec39cb6611d473d818e4607cf59ac573e1f54171506b108b70c

test:
  secret_key_base: d5911c3fcb0095440b5444bad85db7edc0a0cceb991615a3bc65bb2b27b87a59636caffa4fc732b60f506e0b527ce5c318f33309c934f53fc860ae713feacb1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
